### ISSUE TITLE
ACM UM ORG

### ISSUE THREAD

**Issue by andrewhood125** [DasilvaKareem/MemphisACM#1]
@DasilvaKareem I created an org the ACM several years ago. 

https://github.com/acmum

Are you the current president?

**Comment by DasilvaKareem** [comment]
Yep! I am looking for a way to get the website information
On Sep 23, 2016 9:59 PM, Andrew Hood notifications@github.com wrote:@DasilvaKareem I created an org the ACM several years ago. 

https://github.com/acmum

Are you the current president?

**Comment by andrewhood125** [comment]
Invite sent.
